# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sba_zip_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borr_zip', models.TextField(blank=True, null=True)),
                ('mean_agi', models.FloatField(blank=True, null=True)),
                ('total_small_bus', models.BigIntegerField(blank=True, null=True)),
                ('total_sba', models.BigIntegerField(blank=True, null=True)),
                ('total_504', models.BigIntegerField(blank=True, null=True)),
                ('total_7a', models.BigIntegerField(blank=True, null=True)),
                ('sba_per_small_bus', models.FloatField(blank=True, null=True)),
                ('loan_504_per_small_bus', models.FloatField(blank=True, null=True)),
                ('loan_7a_per_small_bus', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sba_zip_level',
                'managed': False,
            },
        ),
    ]
