COMMENT ON TABLE stg_analytics.sba_sfdo IS 'Staging table containing the combined SBA data for the Bay Area';
COMMENT ON COLUMN stg_analytics.sba_sfdo.program IS 'Indicator of whether loan was approved under SBA''s 7(a) or 504 loan program';
COMMENT ON COLUMN stg_analytics.sba_sfdo.borr_name IS 'Borrower name';
COMMENT ON COLUMN stg_analytics.sba_sfdo.borr_street IS 'Borrower street address';
COMMENT ON COLUMN stg_analytics.sba_sfdo.borr_city IS 'Borrower city';
COMMENT ON COLUMN stg_analytics.sba_sfdo.borr_state IS 'Borrower state';
COMMENT ON COLUMN stg_analytics.sba_sfdo.borr_zip IS 'Borrower zip code';
COMMENT ON COLUMN stg_analytics.sba_sfdo.gross_approval IS 'SBA/CDC loan amount';
COMMENT ON COLUMN stg_analytics.sba_sfdo.approval_date IS 'Date the loan was approved';
COMMENT ON COLUMN stg_analytics.sba_sfdo.approval_fiscal_year IS 'Fiscal year the loan was approved';
COMMENT ON COLUMN stg_analytics.sba_sfdo.first_disbursement_date IS 'Date of first loan disbursement (if available)';
COMMENT ON COLUMN stg_analytics.sba_sfdo.delivery_method IS 'Specific delivery method loan was approved under.  See SOP 50 10 5 for definitions and rules for each delivery method.';
COMMENT ON COLUMN stg_analytics.sba_sfdo.subprogram_description IS 'Subprogram description - specific subprogram loan was aproved under.  See SOP 50 10 5 for definitions and rules for each subprogram.';
COMMENT ON COLUMN stg_analytics.sba_sfdo.initial_interest_rate IS 'Initial interest rate - total interest rate (base rate plus spread) at time loan was approved';
COMMENT ON COLUMN stg_analytics.sba_sfdo.term_in_months IS 'Length of loan term';
COMMENT ON COLUMN stg_analytics.sba_sfdo.naics_code IS 'North American Industry Classification System (NAICS) code';
COMMENT ON COLUMN stg_analytics.sba_sfdo.naics_description IS 'North American Industry Classification System (NAICS) description';
COMMENT ON COLUMN stg_analytics.sba_sfdo.franchise_code IS 'Franchise Code';
COMMENT ON COLUMN stg_analytics.sba_sfdo.franchise_name IS 'Franchise Name';
COMMENT ON COLUMN stg_analytics.sba_sfdo.project_county IS 'County where project occurs';
COMMENT ON COLUMN stg_analytics.sba_sfdo.project_state IS 'State where project occurs';
COMMENT ON COLUMN stg_analytics.sba_sfdo.sba_district_office IS 'SBA district office for the loan';
COMMENT ON COLUMN stg_analytics.sba_sfdo.congressional_district IS 'Congressional district office, within each state, for the borrower address';
COMMENT ON COLUMN stg_analytics.sba_sfdo.business_type IS 'Borrower Business Type - Individual, Partnership, or Corporation';
COMMENT ON COLUMN stg_analytics.sba_sfdo.loan_status IS 'Status of the loan. PIF=Paid in Full; EXEMPT=Not Disclosed, treat like Unknown; CHGOFF=Charged Off; NOT FUNDED=Not yet disbursed; CANCLED=Cancelled';
COMMENT ON COLUMN stg_analytics.sba_sfdo.chargeoff_date IS 'Date SBA charged off loan';
COMMENT ON COLUMN stg_analytics.sba_sfdo.gross_chargeoff_amount IS 'Total loan balance charged off (includes guaranteed and non-guaranteed portion of loan)';
COMMENT ON COLUMN stg_analytics.sba_sfdo.jobs_supported IS 'Total Jobs Created + Jobs Retained as reported by lender on SBA Loan Application.  SBA does not review, audit, or validate these numbers - they are simply self-reported, good faith estimates by the lender.';
COMMENT ON COLUMN stg_analytics.sba_sfdo.cdc_name IS 'Community Development Corporation name';
COMMENT ON COLUMN stg_analytics.sba_sfdo.cdc_street IS 'Community Development Corporation street address';
COMMENT ON COLUMN stg_analytics.sba_sfdo.cdc_city IS 'Community Development Corporation city';
COMMENT ON COLUMN stg_analytics.sba_sfdo.cdc_state IS 'Community Development Corporation state';
COMMENT ON COLUMN stg_analytics.sba_sfdo.cdc_zip IS 'Community Development Corporation zip code';
COMMENT ON COLUMN stg_analytics.sba_sfdo.third_party_lender_name IS 'Third Party Lender name';
COMMENT ON COLUMN stg_analytics.sba_sfdo.third_party_lender_city IS 'Third Party Lender city';
COMMENT ON COLUMN stg_analytics.sba_sfdo.third_party_lender_state IS 'Third Party Lender state';
COMMENT ON COLUMN stg_analytics.sba_sfdo.third_party_dollars IS 'Third Party loan amount';
COMMENT ON COLUMN stg_analytics.sba_sfdo.bank_name IS 'Bank name';
COMMENT ON COLUMN stg_analytics.sba_sfdo.bank_street IS 'Bank street address';
COMMENT ON COLUMN stg_analytics.sba_sfdo.bank_city IS 'Bank city';
COMMENT ON COLUMN stg_analytics.sba_sfdo.bank_state IS 'Bank state';
COMMENT ON COLUMN stg_analytics.sba_sfdo.bank_zip IS 'Bank zip code';
COMMENT ON COLUMN stg_analytics.sba_sfdo.sba_guaranteed_approval IS 'Amount of SBA''s loan guaranty';
COMMENT ON COLUMN stg_analytics.sba_sfdo.revolver_status IS 'Indicator of whether a loan is a term loan or revolving line of credit (0=Term, 1=Revolver)';

 