/*
This query takes the sba_sfdo loan data set and joins in data from API calls
*/

drop table if exists stg_analytics.sba_sfdo_all;
create table stg_analytics.sba_sfdo_all
(
sba_sfdo_id bigint primary key,
program text,
borr_name text,
borr_street text,
borr_city text,
borr_state text,
borr_zip text,
gross_approval bigint,
approval_date timestamp without time zone,
approval_fiscal_year bigint,
first_disbursement_date timestamp without time zone,
delivery_method text,
subprogram_description text,
initial_interest_rate double precision,
term_in_months bigint,
naics_code double precision,
naics_description text,
franchise_code text,
franchise_name text,
project_county text,
project_state text,
sba_district_office text,
congressional_district double precision,
business_type text,
loan_status text,
chargeoff_date timestamp without time zone,
gross_chargeoff_amount bigint,
jobs_supported bigint,
cdc_name text,
cdc_street text,
cdc_city text,
cdc_state text,
cdc_zip text,
third_party_lender_name text,
third_party_lender_city text,
third_party_lender_state text,
third_party_dollars double precision,
bank_name text,
bank_street text,
bank_city text,
bank_state text,
bank_zip text,
sba_guaranteed_approval bigint,
revolver_status bigint,
yelp_rating numeric,
yelp_total_reviews bigint,
yelp_url text
);

insert into stg_analytics.sba_sfdo_all

select
  sba_sfdo.sba_sfdo_id,
  sba_sfdo.program,
  sba_sfdo.borr_name,
  sba_sfdo.borr_street,
  sba_sfdo.borr_city,
  sba_sfdo.borr_state,
  sba_sfdo.borr_zip,
  sba_sfdo.gross_approval,
  sba_sfdo.approval_date,
  sba_sfdo.approval_fiscal_year,
  sba_sfdo.first_disbursement_date,
  sba_sfdo.delivery_method,
  sba_sfdo.subprogram_description,
  sba_sfdo.initial_interest_rate,
  sba_sfdo.term_in_months,
  sba_sfdo.naics_code,
  sba_sfdo.naics_description,
  sba_sfdo.franchise_code,
  sba_sfdo.franchise_name,
  sba_sfdo.project_county,
  sba_sfdo.project_state,
  sba_sfdo.sba_district_office,
  sba_sfdo.congressional_district,
  sba_sfdo.business_type,
  sba_sfdo.loan_status,
  sba_sfdo.chargeoff_date,
  sba_sfdo.gross_chargeoff_amount,
  sba_sfdo.jobs_supported,
  sba_sfdo.cdc_name,
  sba_sfdo.cdc_street,
  sba_sfdo.cdc_city,
  sba_sfdo.cdc_state,
  sba_sfdo.cdc_zip,
  sba_sfdo.third_party_lender_name,
  sba_sfdo.third_party_lender_city,
  sba_sfdo.third_party_lender_state,
  sba_sfdo.third_party_dollars,
  sba_sfdo.bank_name,
  sba_sfdo.bank_street,
  sba_sfdo.bank_city,
  sba_sfdo.bank_state,
  sba_sfdo.bank_zip,
  sba_sfdo.sba_guaranteed_approval,
  sba_sfdo.revolver_status,
  api_calls.yelp_rating,
  api_calls.yelp_total_reviews,
  api_calls.yelp_url
from stg_analytics.sba_sfdo as sba_sfdo
  left join stg_analytics.sba_sfdo_api_calls as api_calls
    on sba_sfdo.sba_sfdo_id = api_calls.sba_sfdo_id
