# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBAMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borr_zip', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
